import numpy as np
import pandas as pd
from pathlib import Path

provinces = [
    "Newfoundland and Labrador",
    "Prince Edward Island",
    "Nova Scotia",
    "New Brunswick",
    "Quebec",
    "Ontario",
    "Manitoba",
    "Saskatchewan",
    "Alberta",
    "British Columbia",
    "Yukon",
    "Northwest Territories",
    "Nunavut"
]

specialties = [
    "Internal Medicine",
    "Cardiology",
    "Gastroenterology",
    "Neurology",
    "Psychiatry",
    "Pediatrics",
    "Dermatology",
    "General Surgery",
    "Urology",
    "Orthopedic Surgery",
    "Ophthalmology",
    "Obstetrics/Gynecology"
]

market_context = pd.DataFrame([
    (province, speciality)
    for province in provinces
    for speciality in specialties
],
columns = ['Province', 'Specialty'])

population = {
    "Newfoundland and Labrador": 540500,
    "Prince Edward Island": 175800,
    "Nova Scotia": 1056200,
    "New Brunswick": 835000,
    "Quebec": 8903100,
    "Ontario": 15788400,
    "Manitoba": 1461000,
    "Saskatchewan": 1217700,
    "Alberta": 4734700,
    "British Columbia": 5585500,
    "Yukon": 45700,
    "Northwest Territories": 44300,
    "Nunavut": 40900
}

market_context["Population"] = market_context["Province"].map(population)
physician_data = pd.DataFrame(
    [
        # Province, Specialty, Physician_Count

        ("Newfoundland and Labrador", "Internal Medicine", 64),
        ("Prince Edward Island", "Internal Medicine", 17),
        ("Nova Scotia", "Internal Medicine", 98),
        ("New Brunswick", "Internal Medicine", 70),
        ("Quebec", "Internal Medicine", 945),
        ("Ontario", "Internal Medicine", 1734),
        ("Manitoba", "Internal Medicine", 126),
        ("Saskatchewan", "Internal Medicine", 117),
        ("Alberta", "Internal Medicine", 521),
        ("British Columbia", "Internal Medicine", 673),
        ("Yukon", "Internal Medicine", 0),
        ("Northwest Territories", "Internal Medicine", 1),
        ("Nunavut", "Internal Medicine", 0),

        ("Newfoundland and Labrador", "Cardiology", 18),
        ("Prince Edward Island", "Cardiology", 2),
        ("Nova Scotia", "Cardiology", 54),
        ("New Brunswick", "Cardiology", 35),
        ("Quebec", "Cardiology", 472),
        ("Ontario", "Cardiology", 671),
        ("Manitoba", "Cardiology", 42),
        ("Saskatchewan", "Cardiology", 37),
        ("Alberta", "Cardiology", 167),
        ("British Columbia", "Cardiology", 176),
        ("Yukon", "Cardiology", 0),
        ("Northwest Territories", "Cardiology", 0),
        ("Nunavut", "Cardiology", 0),

        ("Newfoundland and Labrador", "Gastroenterology", 9),
        ("Prince Edward Island", "Gastroenterology", 3),
        ("Nova Scotia", "Gastroenterology", 26),
        ("New Brunswick", "Gastroenterology", 16),
        ("Quebec", "Gastroenterology", 247),
        ("Ontario", "Gastroenterology", 344),
        ("Manitoba", "Gastroenterology", 20),
        ("Saskatchewan", "Gastroenterology", 18),
        ("Alberta", "Gastroenterology", 128),
        ("British Columbia", "Gastroenterology", 102),
        ("Yukon", "Gastroenterology", 0),
        ("Northwest Territories", "Gastroenterology", 0),
        ("Nunavut", "Gastroenterology", 0),

        ("Newfoundland and Labrador", "Neurology", 12),
        ("Prince Edward Island", "Neurology", 3),
        ("Nova Scotia", "Neurology", 33),
        ("New Brunswick", "Neurology", 23),
        ("Quebec", "Neurology", 290),
        ("Ontario", "Neurology", 502),
        ("Manitoba", "Neurology", 43),
        ("Saskatchewan", "Neurology", 35),
        ("Alberta", "Neurology", 206),
        ("British Columbia", "Neurology", 233),
        ("Yukon", "Neurology", 0),
        ("Northwest Territories", "Neurology", 0),
        ("Nunavut", "Neurology", 0),

        ("Newfoundland and Labrador", "Psychiatry", 85),
        ("Prince Edward Island", "Psychiatry", 15),
        ("Nova Scotia", "Psychiatry", 202),
        ("New Brunswick", "Psychiatry", 97),
        ("Quebec", "Psychiatry", 1350),
        ("Ontario", "Psychiatry", 2220),
        ("Manitoba", "Psychiatry", 192),
        ("Saskatchewan", "Psychiatry", 113),
        ("Alberta", "Psychiatry", 679),
        ("British Columbia", "Psychiatry", 973),
        ("Yukon", "Psychiatry", 2),
        ("Northwest Territories", "Psychiatry", 2),
        ("Nunavut", "Psychiatry", 0),

        ("Newfoundland and Labrador", "Pediatrics", 61),
        ("Prince Edward Island", "Pediatrics", 18),
        ("Nova Scotia", "Pediatrics", 103),
        ("New Brunswick", "Pediatrics", 63),
        ("Quebec", "Pediatrics", 702),
        ("Ontario", "Pediatrics", 1372),
        ("Manitoba", "Pediatrics", 143),
        ("Saskatchewan", "Pediatrics", 98),
        ("Alberta", "Pediatrics", 552),
        ("British Columbia", "Pediatrics", 496),
        ("Yukon", "Pediatrics", 3),
        ("Northwest Territories", "Pediatrics", 3),
        ("Nunavut", "Pediatrics", 2),

        ("Newfoundland and Labrador", "Dermatology", 11),
        ("Prince Edward Island", "Dermatology", 2),
        ("Nova Scotia", "Dermatology", 23),
        ("New Brunswick", "Dermatology", 13),
        ("Quebec", "Dermatology", 248),
        ("Ontario", "Dermatology", 256),
        ("Manitoba", "Dermatology", 21),
        ("Saskatchewan", "Dermatology", 11),
        ("Alberta", "Dermatology", 92),
        ("British Columbia", "Dermatology", 95),
        ("Yukon", "Dermatology", 0),
        ("Northwest Territories", "Dermatology", 0),
        ("Nunavut", "Dermatology", 0),

        ("Newfoundland and Labrador", "General Surgery", 65),
        ("Prince Edward Island", "General Surgery", 13),
        ("Nova Scotia", "General Surgery", 68),
        ("New Brunswick", "General Surgery", 61),
        ("Quebec", "General Surgery", 563),
        ("Ontario", "General Surgery", 807),
        ("Manitoba", "General Surgery", 83),
        ("Saskatchewan", "General Surgery", 84),
        ("Alberta", "General Surgery", 195),
        ("British Columbia", "General Surgery", 309),
        ("Yukon", "General Surgery", 5),
        ("Northwest Territories", "General Surgery", 1),
        ("Nunavut", "General Surgery", 0),

        ("Newfoundland and Labrador", "Urology", 13),
        ("Prince Edward Island", "Urology", 4),
        ("Nova Scotia", "Urology", 29),
        ("New Brunswick", "Urology", 25),
        ("Quebec", "Urology", 212),
        ("Ontario", "Urology", 321),
        ("Manitoba", "Urology", 22),
        ("Saskatchewan", "Urology", 17),
        ("Alberta", "Urology", 58),
        ("British Columbia", "Urology", 119),
        ("Yukon", "Urology", 0),
        ("Northwest Territories", "Urology", 0),
        ("Nunavut", "Urology", 0),

        ("Newfoundland and Labrador", "Orthopedic Surgery", 31),
        ("Prince Edward Island", "Orthopedic Surgery", 8),
        ("Nova Scotia", "Orthopedic Surgery", 60),
        ("New Brunswick", "Orthopedic Surgery", 46),
        ("Quebec", "Orthopedic Surgery", 431),
        ("Ontario", "Orthopedic Surgery", 654),
        ("Manitoba", "Orthopedic Surgery", 65),
        ("Saskatchewan", "Orthopedic Surgery", 54),
        ("Alberta", "Orthopedic Surgery", 209),
        ("British Columbia", "Orthopedic Surgery", 301),
        ("Yukon", "Orthopedic Surgery", 1),
        ("Northwest Territories", "Orthopedic Surgery", 1),
        ("Nunavut", "Orthopedic Surgery", 0),

        ("Newfoundland and Labrador", "Ophthalmology", 19),
        ("Prince Edward Island", "Ophthalmology", 6),
        ("Nova Scotia", "Ophthalmology", 58),
        ("New Brunswick", "Ophthalmology", 37),
        ("Quebec", "Ophthalmology", 375),
        ("Ontario", "Ophthalmology", 467),
        ("Manitoba", "Ophthalmology", 38),
        ("Saskatchewan", "Ophthalmology", 30),
        ("Alberta", "Ophthalmology", 131),
        ("British Columbia", "Ophthalmology", 241),
        ("Yukon", "Ophthalmology", 0),
        ("Northwest Territories", "Ophthalmology", 1),
        ("Nunavut", "Ophthalmology", 0),

        ("Newfoundland and Labrador", "Obstetrics/Gynecology", 49),
        ("Prince Edward Island", "Obstetrics/Gynecology", 11),
        ("Nova Scotia", "Obstetrics/Gynecology", 79),
        ("New Brunswick", "Obstetrics/Gynecology", 64),
        ("Quebec", "Obstetrics/Gynecology", 562),
        ("Ontario", "Obstetrics/Gynecology", 976),
        ("Manitoba", "Obstetrics/Gynecology", 100),
        ("Saskatchewan", "Obstetrics/Gynecology", 81),
        ("Alberta", "Obstetrics/Gynecology", 269),
        ("British Columbia", "Obstetrics/Gynecology", 382),
        ("Yukon", "Obstetrics/Gynecology", 4),
        ("Northwest Territories", "Obstetrics/Gynecology", 1),
        ("Nunavut", "Obstetrics/Gynecology", 1)
    ],
    columns=["Province", "Specialty", "Physician_Count"]
)
#print(physician_data.head())
#print("\nNumber of rows:", len(physician_data))
#print(market_context["Population"].isna().sum())

#merging data
market_context = market_context.merge(
    physician_data, on=["Province", "Specialty"], how = "left"
)

market_context["Physicians_per_100k"] =(
    market_context["Physician_Count"] / market_context["Population"]*100000
)
service_data = pd.DataFrame(
    [
        # Province, Specialty, Total consultations and visits

        ("Newfoundland and Labrador", "Internal Medicine", 204038),
        ("Prince Edward Island", "Internal Medicine", 10509),
        ("Nova Scotia", "Internal Medicine", 145180),
        ("New Brunswick", "Internal Medicine", 221150),
        ("Quebec", "Internal Medicine", 7159196),
        ("Ontario", "Internal Medicine", 13644203),
        ("Manitoba", "Internal Medicine", 964395),
        ("Saskatchewan", "Internal Medicine", 489055),
        ("Alberta", "Internal Medicine", 2652189),
        ("British Columbia", "Internal Medicine", 2850985),
        ("Yukon", "Internal Medicine", np.nan),
        ("Northwest Territories", "Internal Medicine", np.nan),
        ("Nunavut", "Internal Medicine", np.nan),

        ("Newfoundland and Labrador", "Cardiology", 26674),
        ("Prince Edward Island", "Cardiology", np.nan),
        ("Nova Scotia", "Cardiology", 18560),
        ("New Brunswick", "Cardiology", 58079),
        ("Quebec", "Cardiology", 1557734),
        ("Ontario", "Cardiology", 1850902),
        ("Manitoba", "Cardiology", 113730),
        ("Saskatchewan", "Cardiology", 85481),
        ("Alberta", "Cardiology", 472844),
        ("British Columbia", "Cardiology", 449957),
        ("Yukon", "Cardiology", np.nan),
        ("Northwest Territories", "Cardiology", np.nan),
        ("Nunavut", "Cardiology", np.nan),

        ("Newfoundland and Labrador", "Gastroenterology", 11484),
        ("Prince Edward Island", "Gastroenterology", np.nan),
        ("Nova Scotia", "Gastroenterology", 8182),
        ("New Brunswick", "Gastroenterology", 48236),
        ("Quebec", "Gastroenterology", 833911),
        ("Ontario", "Gastroenterology", 1050160),
        ("Manitoba", "Gastroenterology", 50523),
        ("Saskatchewan", "Gastroenterology", 41899),
        ("Alberta", "Gastroenterology", 136863),
        ("British Columbia", "Gastroenterology", 259992),
        ("Yukon", "Gastroenterology", np.nan),
        ("Northwest Territories", "Gastroenterology", np.nan),
        ("Nunavut", "Gastroenterology", np.nan),

        ("Newfoundland and Labrador", "Neurology", 12144),
        ("Prince Edward Island", "Neurology", 0),
        ("Nova Scotia", "Neurology", 13474),
        ("New Brunswick", "Neurology", 13623),
        ("Quebec", "Neurology", 590742),
        ("Ontario", "Neurology", 967625),
        ("Manitoba", "Neurology", 89819),
        ("Saskatchewan", "Neurology", 32112),
        ("Alberta", "Neurology", 187727),
        ("British Columbia", "Neurology", 256049),
        ("Yukon", "Neurology", np.nan),
        ("Northwest Territories", "Neurology", np.nan),
        ("Nunavut", "Neurology", np.nan),

        ("Newfoundland and Labrador", "Psychiatry", 50987),
        ("Prince Edward Island", "Psychiatry", 29746),
        ("Nova Scotia", "Psychiatry", 47152),
        ("New Brunswick", "Psychiatry", 78744),
        ("Quebec", "Psychiatry", 2863602),
        ("Ontario", "Psychiatry", 4632344),
        ("Manitoba", "Psychiatry", 419270),
        ("Saskatchewan", "Psychiatry", 171947),
        ("Alberta", "Psychiatry", 2295519),
        ("British Columbia", "Psychiatry", 1654851),
        ("Yukon", "Psychiatry", 95),
        ("Northwest Territories", "Psychiatry", np.nan),
        ("Nunavut", "Psychiatry", np.nan),

        ("Newfoundland and Labrador", "Pediatrics", 32405),
        ("Prince Edward Island", "Pediatrics", 3391),
        ("Nova Scotia", "Pediatrics", 23768),
        ("New Brunswick", "Pediatrics", 35188),
        ("Quebec", "Pediatrics", 1750210),
        ("Ontario", "Pediatrics", 3095592),
        ("Manitoba", "Pediatrics", 324589),
        ("Saskatchewan", "Pediatrics", 79529),
        ("Alberta", "Pediatrics", 955712),
        ("British Columbia", "Pediatrics", 483831),
        ("Yukon", "Pediatrics", 26),
        ("Northwest Territories", "Pediatrics", np.nan),
        ("Nunavut", "Pediatrics", np.nan),

        ("Newfoundland and Labrador", "Dermatology", 52260),
        ("Prince Edward Island", "Dermatology", np.nan),
        ("Nova Scotia", "Dermatology", 45959),
        ("New Brunswick", "Dermatology", 45110),
        ("Quebec", "Dermatology", 768810),
        ("Ontario", "Dermatology", 1302460),
        ("Manitoba", "Dermatology", 88344),
        ("Saskatchewan", "Dermatology", 33961),
        ("Alberta", "Dermatology", 432642),
        ("British Columbia", "Dermatology", 301030),
        ("Yukon", "Dermatology", np.nan),
        ("Northwest Territories", "Dermatology", np.nan),
        ("Nunavut", "Dermatology", np.nan),

        ("Newfoundland and Labrador", "General Surgery", 65448),
        ("Prince Edward Island", "General Surgery", 18082),
        ("Nova Scotia", "General Surgery", 72839),
        ("New Brunswick", "General Surgery", 78242),
        ("Quebec", "General Surgery", 1074674),
        ("Ontario", "General Surgery", 2332027),
        ("Manitoba", "General Surgery", 185064),
        ("Saskatchewan", "General Surgery", 103837),
        ("Alberta", "General Surgery", 379396),
        ("British Columbia", "General Surgery", 521999),
        ("Yukon", "General Surgery", 3101),
        ("Northwest Territories", "General Surgery", np.nan),
        ("Nunavut", "General Surgery", np.nan),

        ("Newfoundland and Labrador", "Urology", 39658),
        ("Prince Edward Island", "Urology", 3035),
        ("Nova Scotia", "Urology", 72065),
        ("New Brunswick", "Urology", 50980),
        ("Quebec", "Urology", 756146),
        ("Ontario", "Urology", 1373441),
        ("Manitoba", "Urology", 77826),
        ("Saskatchewan", "Urology", 31567),
        ("Alberta", "Urology", 195457),
        ("British Columbia", "Urology", 380078),
        ("Yukon", "Urology", np.nan),
        ("Northwest Territories", "Urology", np.nan),
        ("Nunavut", "Urology", np.nan),

        ("Newfoundland and Labrador", "Orthopedic Surgery", 46093),
        ("Prince Edward Island", "Orthopedic Surgery", 22223),
        ("Nova Scotia", "Orthopedic Surgery", 65380),
        ("New Brunswick", "Orthopedic Surgery", 93310),
        ("Quebec", "Orthopedic Surgery", 651198),
        ("Ontario", "Orthopedic Surgery", 2082726),
        ("Manitoba", "Orthopedic Surgery", 129376),
        ("Saskatchewan", "Orthopedic Surgery", 112137),
        ("Alberta", "Orthopedic Surgery", 358195),
        ("British Columbia", "Orthopedic Surgery", 484847),
        ("Yukon", "Orthopedic Surgery", 4110),
        ("Northwest Territories", "Orthopedic Surgery", np.nan),
        ("Nunavut", "Orthopedic Surgery", np.nan),

        ("Newfoundland and Labrador", "Ophthalmology", 52381),
        ("Prince Edward Island", "Ophthalmology", 17821),
        ("Nova Scotia", "Ophthalmology", 168691),
        ("New Brunswick", "Ophthalmology", 109320),
        ("Quebec", "Ophthalmology", 1466150),
        ("Ontario", "Ophthalmology", 3252932),
        ("Manitoba", "Ophthalmology", 130850),
        ("Saskatchewan", "Ophthalmology", 184544),
        ("Alberta", "Ophthalmology", 699265),
        ("British Columbia", "Ophthalmology", 771735),
        ("Yukon", "Ophthalmology", np.nan),
        ("Northwest Territories", "Ophthalmology", np.nan),
        ("Nunavut", "Ophthalmology", np.nan),

        ("Newfoundland and Labrador", "Obstetrics/Gynecology", 76377),
        ("Prince Edward Island", "Obstetrics/Gynecology", 1581),
        ("Nova Scotia", "Obstetrics/Gynecology", 36662),
        ("New Brunswick", "Obstetrics/Gynecology", 83415),
        ("Quebec", "Obstetrics/Gynecology", 1129770),
        ("Ontario", "Obstetrics/Gynecology", 3154859),
        ("Manitoba", "Obstetrics/Gynecology", 241359),
        ("Saskatchewan", "Obstetrics/Gynecology", 127873),
        ("Alberta", "Obstetrics/Gynecology", 619900),
        ("British Columbia", "Obstetrics/Gynecology", 544338),
        ("Yukon", "Obstetrics/Gynecology", 1931),
        ("Northwest Territories", "Obstetrics/Gynecology", np.nan),
        ("Nunavut", "Obstetrics/Gynecology", np.nan)
    ],
    columns=["Province", "Specialty", "Service_Volume"]
)

market_context = market_context.merge(
    service_data, on = ["Province","Specialty"], how="left"
)

market_context["Services_per_Physician"] = np.where(
    market_context["Physician_Count"] > 0,
    market_context["Service_Volume"] / market_context["Physician_Count"],
    np.nan
)
market_context.to_csv(
    Path(__file__).resolve().parent / "Data" / "market_context.csv",
    index=False
)

print("Market context saved.")

